### ISSUE TITLE
Unable to connect to Destination service using cloud-sdk and JDK11

### ISSUE THREAD

**Issue by biswaranjanray** [SAP/cloud-security-xsuaa-integration#1009]
Hi,

We're recommended by cloud-sdk team to reach you out for an issue that we're facing in our application while connecting to destination service. The issue was elaborately discussed [here](https://github.com/SAP/cloud-sdk/issues/1035) with the cloud-sdk team earlier.

The below tech stack doesn't work for us and throws exceptions when the app tries to connect to destination service.
Java 11
Cloud-SDK 3.74.0
Spring-XSUAA 2.12.3
Buildpack: https://github.com/cloudfoundry/java-buildpack.git

However we could able to fix the issue and could able to connect to the destination service by replacing the java community buildpack with sap_java_buildpack. You may refer our application [here](https://github.tools.sap/refapps/cloud-espm-cloud-native).

Any suggestions.

Best Regards,
Biswa Ranjan Ray

**Comment by liga-oz** [comment]
Hi @biswaranjanray,

thanks for reporting this issue. We've seen in the past classloader issues with sap_java_buildpack and those were fixed by buildpack team as far as I'm aware, but I can't recall whether they were with Java 8 or 11. 

Nevertheless, we test the library with Java 8 and 11 using sap_java_buildpack and there haven't been any problems. If you don't have any objections against sap_java_buildpack, I would suggest to stick with that.

Regarding the community buildpack perhaps the issue with classloader is the same what sap_java_buildpack has already fixed, but anyways the issue is within the buildpack itself - strategy how classes are loaded. 

I've looked up community buildpack github issues and found that there have been reported class loader issues with Java 9,10,11, could be related https://github.com/cloudfoundry/java-buildpack/issues/585#issuecomment-425412444 there are some workarounds described as well, if you wish you can adjust the workarounds and experiment to see if that helps.

Kind Regards,
Liga

**Comment by biswaranjanray** [comment]
Hi @liga-oz,

Thank you for your quick response and the clarifications.
As you mentioned it could be classloader issues and since you already have observed in community buildpack github, there are classloader issues reported with JDK 9,10,11 so it make sense for us to stick to sap_java_buildpack. 

Thanks again for sharing the link to the workarounds discussed for java community buildpack issues, we might explore it in case its required to support java community buildpack also in our application. 

Best Regards,
Biswa Ranjan Ray
