### ISSUE TITLE
Starter configuration RestTemplate issue

### ISSUE THREAD

**Issue by rage28** [SAP/cloud-security-xsuaa-integration#252]
Issue:
The RestTemplate class exposed as a RestOperation causes bean conflict in certain scenarios

Description:
- RestTemplate bean is exposed with type [RestOperations](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfiguration.java#L77)
- Consider, a project which uses this library also exposes a RestTemplate bean
- If any class requests for a RestTemplate bean to be autowired/injected it will fail due to bean conflict with the following message

```
***************************
APPLICATION FAILED TO START
***************************

Description:
Parameter 1 of method xsuaaJwtDecoder in com.sap.cloud.security.xsuaa.autoconfiguration.XsuaaResourceServerJwkAutoConfiguration required a single bean, but 2 were found:
	- xsuaaRestOperations: defined by method 'xsuaaRestOperations' in class path resource [com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfiguration.class]
	- restTemplate: defined by method 'restTemplate' in com.example.app.AppConfiguration

Action:
Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Solution:
Consider making the return type RestTemplate instead of RestOperation

**Comment by nenaraab** [comment]
Hi @rage28,

not sure whether i've fully understood the problem, as we've implemented it as `@ConditionalOnMissingBean` and RestTemplate is considered as well, as it is subclass of `RestOperations`:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfiguration.java#L76

and there is a test for that:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfigurationTest.java#L104

Can you please provide me the code of `com.example.app.AppConfiguration` - in particular how you've configured your RestTemplate bean?

Best regards,
Nena

**Comment by ttrabold** [comment]
Hi @nenaraab ,

we also have issues with the injection of the RestOperations bean in `XsuaaResourceServerJwkAutoConfiguration`.
As we have multiple RestTemplates defined in our application (but no bean of `RestOperations` type), the injection mechanism does not work, since spring finds multiple `RestTemplate` (which implement the `RestOperations` interface) beans.
Currently you define a RestOperations bean in `XsuaaAutoConfiguration` but with the ConditionalOnMissingBean. Can't you just change your RestOperations bean definition to: 

```java
@Bean
@Qualifier("restOperations")
public RestOperations restOperations() {
    return new RestTemplate();
}
```

**Comment by nenaraab** [comment]
Hi @ttrabold, @rage28,

thanks a lot for reporting. 

I have two questions for reproduction...
- Do I understand correct, in case you define other RestTemplates with explicit qualifiers, then the spring-xsuaa auto-configuration does not know, which one to choose? Is that correct?

- Is it right, that in case you define other RestTemplates our restOperations bean is not created because of `ConditionalOnMissingBean`.

Thanks!

**Comment by ttrabold** [comment]
Hi @nenaraab ,

* I cannot confirm the first point, since we do not qualify each and every `RestTemplate` with a name. However, it is not the xsuaa autoconfig I guess but the spring IoC container who does not know which `RestOperations` bean to use since there are multiple ones available. The spring mechanism takes basically takes type, qualifier and name into account (https://www.baeldung.com/spring-annotations-resource-inject-autowire#Autowired) for bean injection. Since name and qualifier do not match, it finds multiple ones of the same type. I think this is the problem here.

* Yes, this is correct. Since there already are `RestOperations` beans available, the `@ConditionalOnMissingBean` triggers and does not create the `RestOperations` with your function.

**Comment by nenaraab** [comment]
Hi @ttrabold, @rage28,

it should be fixed in the master branch. If you like to test it, you can clone the repo
https://github.com/SAP/cloud-security-xsuaa-integration
and perform locally
`mvn clean install`
You need to switch to version `2.5.3`.

Please replace your autoconfiguration with a configuration that declares only a xsuaaRestOperations
bean as documented here: https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa#resttemplate--restoperations

Happy to receive your feedback!

Thanks and best regards,
Nena

**Comment by nenaraab** [comment]
Please consider the spring-xsuaa documentation to see, how to setup your project properly:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa
