### ISSUE TITLE
How to make index html authenticated ?

### ISSUE THREAD

**Issue by tnpradeep** [SAP/cloud-security-xsuaa-integration#263]
Hello,

I have a web application similar to your [sap-java-buildpack-api-usage](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/samples/sap-java-buildpack-api-usage), but with index.html in addition with below structure

src
--main
----java
----webapp
------index.html
 ------WEB_INF
 --------web.xml

And web.xml has login-config as below
```
  <login-config> 
    <auth-method>XSUAA</auth-method>
  </login-config> 
```
And I also have a approuter for this with xsuaa authentication specified in the route as below
`"authenticationType": "xsuaa"`

Now when i use the approuter url to access the application then it asks for login, but when I use the application url directly then it opens the index.html without asking for login.

Please suggest how I can protect index.html ?

**Comment by nenaraab** [comment]
Hi @tnpradeep 

you need to protect your resources and your endpoints as part of your application, so that nobody is able to access them directly.

The approuter serves static content, so why not put and protect it as part of the approuter?

Example:
https://github.com/SAP-samples/cloud-bulletinboard-ads/blob/solution-24-Make-App-Secure-Spring5/src/main/approuter/resources/index.html

Docu:
https://github.com/SAP-samples/cloud-bulletinboard-ads/blob/Documentation/Security/Exercise_22_DeployApplicationRouter.md

Best regards,
Nena

**Comment by tnpradeep** [comment]
Thank you for the suggestion,
But in our case index.html is closely related with other UI resources, so it can't be moved to approuter.
