### ISSUE TITLE
Potential Memory Leak in JwtValidatorBuilder

### ISSUE THREAD

**Issue by MatKuhr** [SAP/cloud-security-xsuaa-integration#307]
Hi,
We noticed that using the `JwtValidatorBuilder` in a non-efficient way leads to a memory leak. We were using it like this:

```java
JwtValidatorBuilder.getInstance(getXsuaaConfiguration()).build();
```

Where `getXsuaaConfiguration()` would load the XSUAA configuration which meant creating a new instance for it.

We were not aware that the `JwtValidatorBuilder.getInstance` method stores all builder instances in a map where the configuration object serves as key. In our case this is a problem because the configuration object is always a different instance and there is no equals implemented on it. That means when `getInstance` [performs the lookup](https://github.com/SAP/cloud-security-xsuaa-integration/blob/8164c7ca041f57b40713a681ec19d231539f2031/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java#L50) to see if there is already a builder registered it will only find one if the XSUAA configuration object is exactly the same instance as the one in the map.

To us it wasn't obvious that the instances would be stored. It may be worthwhile to make this part of the code more resilient against such usage. E.g. implement `equals` on the configuration or limit the map in size.

We now avoid the problem by making sure we use the same instances of configuration objects in all parts of our code. So I just wanted to let you know because this might be a problem others run into as well.

**Comment by hassler-d** [comment]
> That means when getInstance performs the lookup to see if there is already a builder registered it will only find one if the XSUAA configuration object is exactly the same instance as the one in the map.

Yes that is correct. Always calling this method with fresh configuration instances will result in a memory leak. Implementing `equals` on the configuration will fix this if the configuration stays the same. Same as defined by the (not yet implemented) `equals` method.

> In our case this is a problem because the configuration object is always a different instance and there is no equals implemented on it.

@MatKuhr By *different* you mean different instance and not also different in content, right?

## Possbile solutions

To fix this I think we could either remove the map or implement the `equals` like @MatKuhr suggested. However, implementing `equals` would only help if the content of the configuration does not change.

### Removing the map

Not saving the `JwtValidatorBuilder` instances would get rid of the memory leak. But it is there for a reason. @nenaraab I think this map has been added for performance reasons, right? So I guess we cannot get rid of it.

### Implementing equals

If the content of the configuration does not change, we can fix this by implement `equals` on the configuration implementation. Then there would only be one `JwtValidatorBuilder` instance for the same configuration object regardless if it is a new instance or the same.

Technically we would still have a memory leak because the instances are never removed from the map. Therefore I propose that we additionally replace this map with a proper cache, e.g. caffeine that restricts its size.

@nenaraab what do you think?

**Comment by MatKuhr** [comment]
> @MatKuhr By different you mean different instance and not also different in content, right?

Yes that is correct. We simply didn't have the same instance available at different places in the code, but the content would be the same when loading again.

And I would imagine that this is to be expected, so there might be a couple of configurations an application is using but usually not an unlimited amount, right? And the `JwtValidationBuilder` might not even rely on every single property of the configuration, so maybe it would also be enough to compare only relevant properties...

**Comment by hassler-d** [comment]
> > @MatKuhr By different you mean different instance and not also different in content, right?
> 
> Yes that is correct. We simply didn't have the same instance available at different places in the code, but the content would be the same when loading again.

Perfect. The `equals` implementation would then be sufficient to fix your problem.

> And I would imagine that this is to be expected, so there might be a couple of configurations an application is using but usually not an unlimited amount, right? 

I agree.

> And the `JwtValidationBuilder` might not even rely on every single property of the configuration, so maybe it would also be enough to compare only relevant properties...

Yes, it might be able to ignore certain parts. But I am not in a position to decide what properties do not matter in regard to the configuration identity.
I think it is best to start with a `equals` that compares the complete content.

Problem is that I cannot start implementing this until June 24th because I am on vacation starting tomorrow. @MatKuhr you don't need this asap because you have already described your workaround, right?

**Comment by MatKuhr** [comment]
Perfect! 
Yes, we now changed our implementation such that the specific instances are available everywhere where they are needed via static variables. So this is not critical for us.

**Comment by nenaraab** [comment]
Hi @hassler-d 
please implement equals and hashcode for the configuration object, i think thats all to limit the number of instances.
