### ISSUE TITLE
Client Credentials for OAuth 2.0 service in SCP Neo

### ISSUE THREAD

**Issue by StueberMa** [SAP/cloud-security-xsuaa-integration#318]
For one of our integration scenarios we need to call an application hosted in SCP Neo. This application provides an OAuth 2.0 service for authentication purposes. I tried to retrieve a client credentials token via the `ClientCredentialsTokenFlow` which results in a `401` with the message `{ "error": "unauthorized_client" }`.

According to your documentation the `ClientCredentialsTokenFlow` should be compliant to [rfc6749](https://tools.ietf.org/html/rfc6749#section-4.4.2). However, in contrast to the RFC [no authentication header](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java#L100) is send for the client credential grant.

**Comment by nenaraab** [comment]
Hi @StueberMa 

yes you are right!

We faced encoding issues with Basic Authorization header, don't remember the details. So that we have adapted all client libs to send client_id / client_secret via request parameter instead of Basic Authorization header. They are now encoded using the
"application/x-www-form-urlencoded" encoding algorithm.

Reference to UAA token flows:
https://docs.cloudfoundry.org/api/uaa/version/74.21.0/index.html#client-credentials-grant

cc @strehle

**Comment by StueberMa** [comment]
Thanks for the reply @nenaraab 

Since CF UAA supports both modes would it be possible to extend this library to allow toggling how client credentials are transferred - body or authorization header?

If you lack resources I might find time tomorrow to file the changes as PR ...

**Comment by mwdb** [comment]
Basic authentication is rather problematic, see https://github.com/cloudfoundry/uaa/issues/778
Form parameters mitigate this issue.

**Comment by nenaraab** [comment]
Hi @mwdb 
thanks for referencing the issue.

**Comment by nenaraab** [comment]
Closing the ticket as we will not support client_id/secret as part of the Basic Authorization header.
