### ISSUE TITLE
Logging: Avoid "IAS not supported" message

### ISSUE THREAD

**Issue by MatKuhr** [SAP/cloud-security-xsuaa-integration#349]
Hi,

we discovered that we still see the following log messages:

```
IAS Service is not yet supported!!!
```

We are using `CFEnvironment.getInstance()` to then use `loadForServicePlan(XSUAA, ...)`. But we see that within `getInstance` an attempt is made to load all configurations, including `IAS` via `CFEnvParser.loadAll(...)`. This is where the above log statements are printed out.

Do you have advice if we should use something else? I looked at the demo application and see that there the configuration is `autowired`. But in the Cloud SDK we can't use that as we want to get all XSUAA configurations.

Or would you consider not loading `IAS` by default but only on demand since it is not supported yet?

**Comment by hassler-d** [comment]
Hello,

this should only be printed once because whenever `CFEnvironment` is accessed the first time, it parses the environment and caches all available configurations. This is when the `Service.IAS` is called and the log statement is printed. The log statement should be visible even before you call `loadForServicePlan` but only once per application start.

We are logging this because if a library user happens to try to manually load an IAS configuration then this message is printed as a warning. The user should be warned because this feature is not completed yet. We have added this to try our IAS PoC applications. Sadly it is logged once per application start even if the library user never tries to access the IAS configuration.

We should are getting rid of this log message as soon as our IAS integration is stabilized. 

Is it printed several times in your case? If so, what version of the library are you using?

Best Regards
Daniel

**Comment by nenaraab** [comment]
As of version [2.7.1](https://github.com/SAP/cloud-security-xsuaa-integration/releases/tag/2.7.1) the message should only appear once at application start up.
