### ISSUE TITLE
How to propagate RequestAttributes and SecurityContext to async thread

### ISSUE THREAD

**Issue by RuchiDhiman** [SAP/cloud-security-xsuaa-integration#469]
Hi Colleague,

how do I transfer RequestAttributes and SecurityContext to an async thread?

Greetings,
Ruchi

**Comment by nenaraab** [comment]
Hi @RuchiDhiman 

pls have a look at this sample, its similar but instead of the SecurityContext it provides the correlationId from the Logger context of main thread into the other thread:

- documentation: 
https://github.com/SAP-samples/cloud-bulletinboard-ads/blob/Documentation/Service2ServiceCommunication/Exercise_19_Transfer_CorrelationID.md
- commit that documents the change:  
https://github.com/SAP-samples/cloud-bulletinboard-ads/commit/74c6473abf9aa33dc15003fe53f5e17154c6ed78

Is this solution applicable?
Which SecurityContext do you make use of?

Best regards,
Nena

**Comment by RuchiDhiman** [comment]
Hi Nena,

if there are a lot of things to propagate the async method interface can become too big. Is there an alternative way to provide some context with Request Attributes, SecurityContext, MDC Context Map ..?

Greetings,
Ruchi

**Comment by nenaraab** [comment]
Hi @RuchiDhiman 
which client lib do you make use of?
Best regards,
Nena

**Comment by RuchiDhiman** [comment]
I am not sure. Cloud SDK?
https://github.wdf.sap.corp/GRC-CH/AutomatedProcedures/blob/6298a39a4fd00a76ae772cf3f82ad0b89834b569/systemtests-helper/srv/pom.xml

**Comment by nenaraab** [comment]
Hi @RuchiDhiman 

actually, I can see two: 
- java-security - maybe via cloud sdk and 
- spring-xsuaa (Spring)

are you implementing a cloud-sdk app or a spring app?

**Comment by RuchiDhiman** [comment]
We dont want to use cloud sdk. In my Pull Request I am experimenting with cloud sdk since it provides some Classes for propagating authtoken, tenant etc.

**Comment by nenaraab** [comment]
Unfortunately you didn't answered my question... whether you like to develop a spring or a java service.  

In case you like to use `spring-xsuaa` you can configure `SecurityContextHolder` with `MODE_INHERITABLETHREADLOCAL`. 
> :bulb: Using MODE_INHERITABLETHREADLOCAL can result in a thread pool containing threads with the wrong security context for async tasks. A better approach is to use an executor that delegates the security context when it runs the task.
 see also: https://github.com/spring-projects/spring-security/issues/6856#issuecomment-518787966

Further reference: https://www.baeldung.com/spring-security-async-principal-propagation
 
In case of `java-security` there is no support for `InheritableThreadLocal` at all, because of the above mentioned reason.

Please open a new issue, in case you have a more detailed request.

Best regards,
Nena
