### ISSUE TITLE
Provide BoM

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-xsuaa-integration#635]
**Describe the solution you'd like**
Provide a BoM: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms to avoid that `java-api` version and `token-client` version do not match.

**Describe alternatives you've considered**
Provide automatic PRs for consumers to upgrade to latest version. Not sure whether this is possible from Github to private Guthub.

**Comment by liga-oz** [comment]
as agreed in the call with @nenaraab, we will stay with the current name `parent` for the bom to avoid incompatible change as there might be users who already use it in the dependencyManagement definition. If you wish to add com.sap.cloud.security.xsuaa BOM add it to your project's pom like described in the comment above.

**Comment by beckermarc** [comment]
Hi @nenaraab @liga-oz 

today we ran into yet another issue in CAP / Cloud SDK due to inconsistent XSUAA versions across different dependencies. The latest version of CAP requires 2.11.3 and Cloud SDK still uses 2.11.0. This leads to classloading issues at runtime, as some XSUAA dependencies are transitively pulled in via Cloud SDK and some via CAP and they don't work together.

I remembered that we had the BOM discussion quite a while ago and checked this issue again and was happy to see that you thought about this and apparently provided a solution for this.

However I took a closer look at the parent POM that you suggest to use and see a major downside to using it: You are managing far more dependencies than just the XSUAA modules. This makes sense as a parent POM, but has quite some issues as a BOM POM. When using your XSUAA BOM POM you are also forcing your versions of various other libraries (Spring, JUnit, Apache HTTP Client, etc.) onto the application that uses your BOM. It would be much better if you leave the control of that to the applications, by just providing a BOM that only contains the XSUAA modules. In the end such a BOM helps to achieve what you actually want: Pull in XSUAA modules in a consistent version.

Could you mabe reevaluate this and think about providing such a BOM POM that only manages the XSUAA modules?

**Comment by nenaraab** [comment]
Hi @liga-oz the request for a slim BoM makes sense, so let’s try to provide that in addition.

**Comment by beckermarc** [comment]
Thanks! 🚀

**Comment by beckermarc** [comment]
Looks like `java-bom` that should have been released with `2.11.6` is not uploaded to Maven Central yet: https://repo1.maven.org/maven2/com/sap/cloud/security/java-bom

**Comment by nenaraab** [comment]
@beckermarc, thanks for the hint, pls see #753 - we need to create another release, version `2.11.6` is corrupt and we have to adapt one of our sample to test the same.
