### ISSUE TITLE
Using token-client for other backing services and creating the HttpClient with mTLS configuration

### ISSUE THREAD

**Issue by fbunsmann** [SAP/cloud-security-xsuaa-integration#679]
**Question Summary**
- Library: `token-client`
- Environment: Cloud Foundry

We are currently evaluating whether we can use the `token-client` library for obtaining jwt tokens within our CAP Sprint Boot Application running in Cloud Foundry. Authentication should be done with mTLS. In this regard we have two questions:

- We have multiple backing services which expose uaa credentials for token retrieval. As far as I saw the `XsuaaAutoConfiguration` only creates an `XsuaaTokenFlows` bean which is configured for the `xsuaa` service binding. How would you propose to obtain tokens for other services?
- The documentation mentions that the `DefaultHttpClientFactory` is not recommended for productive use. Could you elaborate a bit why this is not the case. Would `SSLContextFactory` be safe to use regardless?

Regards,
Florian

**Comment by liga-oz** [comment]
HI @fbunsmann,

`XsuaaTokenFlows` is specifically designed for communication with Xsuaa service. If your backing services also uses Xsuaa as authorization service then theoretically you can create for each service a dedicated XsuaaTokenFlow where you need to provide service's OAuth2 configuration to initialize the bean. Similar like below:

```java
//xsuaaServiceConfiguration=your OAuth2 config of your backing service 
OAuth2ServiceEndpointsProvider endpointsProvider = new XsuaaDefaultEndpoints(xsuaaServiceConfiguration);
ClientIdentity clientCredentials = xsuaaServiceConfiguration.getClientIdentity();
OAuth2TokenService oAuth2TokenService = new XsuaaOAuth2TokenService(xsuaaRestOperations);

new XsuaaTokenFlows(oAuth2TokenService, endpointsProvider, clientCredentials);
```

Regarding `DefaultHttpClientFactory`, it is not fine tuned for your specific use case, things like timeouts, redirect policies etc are not adapted/set and therefore we recommend to use your own customised `httpClient` that you have tested and adapted to your requirements instead of the default one.

Kind Regards,
Liga

**Comment by nenaraab** [comment]
Hi @fbunsmann I've improved the description a little bit and hope it gets clearer. `SSLContextFactory` context is okay for productive usage and will be used by cloud-sdk.
https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/token-client/README.md#new-warning-in-productive-environment-provide-well-configured-httpclientfactory-service

**Comment by fbunsmann** [comment]
Hi @nenaraab and @liga-oz,

thanks for your explanations and the additional documentation regarding the configuration of `HttpClient`. That answers all my questions.

Best Regards,
Florian
